### ISSUE TITLE
init command fails with TypeError: invalid file

### ISSUE THREAD

**Issue by ngulden** [knowsuchagency/hugo_jupyter#2]
* Hugo Jupyter version: 0.1.4
* Python version: 3.5.2
* Operating System: Ubuntu 16.04 LTS

### Description

I wanted to try Hugo Jupyter with a fresh setup Hugo site. The init command failed.

### What I Did

1. I installed Hugo Jupyter via pip. 
1. I tried to setup Hugo Jupyter and run the command `hugo_jupyter --init` on the command line.
1. The command gives the following traceback:

```
$ hugo_jupyter --init
Traceback (most recent call last):
  File "/home/user/.virtualenvs/hugo_jupyter/bin/hugo_jupyter", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/hugo_jupyter/lib/python3.5/site-packages/hugo_jupyter/cli.py", line 33, in main
    with open(Path(Path(__file__).parent, '__fabfile.py')) as fp:
TypeError: invalid file: PosixPath('/home/user/.virtualenvs/hugo_jupyter/lib/python3.5/site-packages/hugo_jupyter/__fabfile.py')
```

**Comment by knowsuchagency** [comment]
Thanks for submitting the issue. 

Latest release should fix the problem by using pkg_resources api as opposed to manual filepaths.
