### ISSUE TITLE
SyntaxError during initialization

### ISSUE THREAD

**Issue by utkuufuk** [knowsuchagency/hugo_jupyter#7]
* Hugo Jupyter version: 1.0.2
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description
Hi, after the installation of `hugo_jupyter`, I run the initialization command as follows:
`hugo_jupyter --init`

Then I get the following error:
```
Successfully initialized. From this directory, the following commands are available.
Just remember to prepend them with `fab`

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fabric/main.py", line 672, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/local/lib/python3.5/dist-packages/fabric/main.py", line 173, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/utku/Github/quickstart/fabfile.py", line 226
    notebook_path: Path = Path(notebook)
                 ^
SyntaxError: invalid syntax
```

I would appreciate if you could help me out. Thanks!

**Comment by Carl-Lejerskar** [comment]
Did you ever resolve this problem? I'm running into it myself!

**Comment by utkuufuk** [comment]
@Carl-Lejerskar No I haven't been able to resolve the problem, and I switched to Hexo for that reason.
